# -*- coding: utf-8 -*-
"""PROYECTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VXqxICpuTzKKJKXvjjqTfonDJZNK5TE
"""

import streamlit as st
import numpy as np
import pandas as pd
import plotly as py # Importación base

# --- CONFIGURACIÓN Y ESTILOS ---
st.set_page_config(page_title="Gasoducto Trans-Andino", layout="wide")
st.title("🚀 Sistema de Simulación y Optimización: Gasoducto Trans-Andino")
st.markdown("---")

# --- 1. PANEL DE CONFIGURACIÓN (SIDEBAR) ---
st.sidebar.header("⚙️ Configuración del Proyecto")

with st.sidebar.expander("💰 Parámetros Económicos", expanded=True):
    costo_energia = st.number_input("Costo Energía (USD/kWh)", value=0.12)
    tasa_interes = st.slider("Tasa de Interés (%)", 1, 20, 10) / 100
    vida_util = 20

with st.sidebar.expander("🛠️ Selección de Material", expanded=True):
    tuberias = {
        "12\"": {"D_ext": 323.8, "t": 10.31, "costo": 185},
        "16\"": {"D_ext": 406.4, "t": 12.70, "costo": 260},
        "20\"": {"D_ext": 508.0, "t": 15.09, "costo": 350},
        "24\"": {"D_ext": 609.6, "t": 17.48, "costo": 440}
    }
    grados_acero = {
        "X52": {"SMYS": 52000, "F": 0.72},
        "X60": {"SMYS": 60000, "F": 0.72}
    }
    sel_d = st.selectbox("Diámetro Nominal", list(tuberias.keys()))
    sel_grado = st.selectbox("Grado del Acero", list(grados_acero.keys()))
    datos_t = tuberias[sel_d]
    datos_g = grados_acero[sel_grado]

with st.sidebar.expander("📊 Variables Operativas", expanded=True):
    Q_mmsfcd = st.number_input("Flujo de Gas (Q) [MMSCFD]", value=500.0)
    N = st.slider("Número de Estaciones (N)", 1, 8, 2)

# --- CONSTANTES TÉCNICAS ---
L_total, P_in_req, P_min_entrega = 400.0, 800.0, 500.0
G, Z, T1_K, k, n_comp, R_gas = 0.65, 0.90, 293.15, 1.3, 0.85, 10.73

# --- 2. FUNCIÓN DE CÁLCULO INTEGRAL ---
def ejecutar_simulacion(D_nom, N_est, Q_val):
    dt = tuberias[D_nom]
    dg = grados_acero[sel_grado]
    d_in = (dt["D_ext"] - 2 * dt["t"]) / 25.4
    L_tramo_mi = (L_total / N_est) * 0.621371
    T1_R = T1_K * 1.8

    # Hidráulica (Weymouth)
    const_W, E_eff = 433.5, 0.92
    caida_tramo = (const_W * (Q_val / E_eff)**2 * (L_tramo_mi * G * T1_R * Z)) / (d_in**5.33)

    distancias, presiones, temperaturas, hp_por_estacion = [0.0], [P_in_req], [20.0], []
    P_actual = P_in_req
    viabilidad = True
    P_entrega_final = 0

    for i in range(N_est):
        arg = P_actual**2 - caida_tramo
        if arg <= 0:
            viabilidad = False
            break

        P_final_tramo = np.sqrt(arg)
        distancias.append(float((i + 1) * (L_total / N_est)))
        presiones.append(P_final_tramo)

        ratio = P_in_req / P_final_tramo
        potencia = (Q_val * 1e6 / (24 * 3600 * n_comp)) * \
                  (Z * R_gas * T1_R / (550 * (k - 1))) * \
                  (ratio**((k - 1) / k) - 1)

        hp_por_estacion.append(potencia)
        temperaturas.append((T1_K * (ratio**((k - 1) / k))) - 273.15)

        if i < N_est - 1:
            distancias.append(float((i + 1) * (L_total / N_est)))
            presiones.append(P_in_req)
            P_actual = P_in_req
        else:
            P_entrega_final = P_final_tramo

    if not viabilidad or P_entrega_final < P_min_entrega:
        viabilidad = False

    MAOP = (2 * dg["SMYS"] * (dt["t"] / 25.4) * dg["F"]) / (dt["D_ext"] / 25.4)
    if P_in_req > MAOP:
        viabilidad = False

    hp_total = sum(hp_por_estacion)
    CAPEX = (dt["costo"] * L_total * 1000) + (hp_total * 1500)
    CRF = (tasa_interes * (1 + tasa_interes)**vida_util) / ((1 + tasa_interes)**vida_util - 1)
    OPEX = hp_total * 0.7457 * 24 * 365 * costo_energia
    TAC = (CAPEX * CRF) + OPEX

    return TAC, hp_total, P_entrega_final, distancias, presiones, temperaturas, viabilidad, MAOP

# --- 3. EJECUCIÓN Y VISUALIZACIÓN ---
TAC, HP_total, P_final, dists, press, temps, ok, maop_val = ejecutar_simulacion(sel_d, N, Q_mmsfcd)

m1, m2, m3 = st.columns(3)
m1.metric("TAC Total (Anual)", f"${TAC/1e6:.2f} MM USD")
m2.metric("Potencia Instalada", f"{HP_total:,.0f} HP")
m3.metric("Presión Final", f"{P_final:.1f} psia")

# --- GRÁFICO USANDO DICCIONARIO DE DATOS (SIN EXPRESS NI GRAPH_OBJECTS) ---
# Esta es la forma más cruda de pasar datos a Plotly
fig = {
    "data": [{
        "x": dists,
        "y": press,
        "type": "scatter",
        "mode": "lines+markers",
        "marker": {"color": "#00CC96"},
        "name": "Perfil de Presión"
    },
    {
        "x": [0, L_total],
        "y": [P_min_entrega, P_min_entrega],
        "type": "scatter",
        "mode": "lines",
        "line": {"dash": "dash", "color": "red"},
        "name": "Límite Entrega"
    }],
    "layout": {
        "title": "📈 Perfil de Presión a lo largo del Gasoducto",
        "xaxis": {"title": "Distancia [km]"},
        "yaxis": {"title": "Presión [psia]"},
        "template": "plotly_white"
    }
}

st.plotly_chart(fig, use_container_width=True)

# --- VALIDACIONES ---
st.subheader("🛡️ Validación de Seguridad y Operación")
cv1, cv2, cv3 = st.columns(3)
with cv1:
    if P_in_req <= maop_val:
        st.success(f"MAOP Seguro: {maop_val:.0f} psi")
    else:
        st.error("FALLA MAOP")

with cv2:
    t_max = max(temps)
    if t_max <= 65:
        st.success(f"Temp. Segura: {t_max:.1f} °C")
    else:
        st.error(f"FALLA TÉRMICA")

with cv3:
    if ok:
        st.success("Entrega Exitosa")
    else:
        st.error("PRESIÓN INVIABLE")

# --- 4. SECCIÓN DE OPTIMIZACIÓN ---
st.markdown("---")
st.subheader("🤖 Algoritmo de Optimización Automática")
if st.button("🚀 Buscar Configuración de Mínimo Costo"):
    res = []
    for d_opt in tuberias.keys():
        for n_opt in range(1, 9):
            t_o, h_o, p_o, _, _, _, viable, _ = ejecutar_simulacion(d_opt, n_opt, Q_mmsfcd)
            if viable:
                res.append({
                    "Diámetro": d_opt,
                    "Estaciones": n_opt,
                    "TAC [MM USD]": t_o / 1e6,
                    "HP": int(h_o)
                })

    if res:
        df_res = pd.DataFrame(res).sort_values("TAC [MM USD]")
        st.write("Top 5 mejores configuraciones:")
        st.table(df_res.head(5).style.format({"TAC [MM USD]": "{:.2f}"}))
    else:
        st.error("No hay configuraciones viables.")